"""Temporal burst segmentation for single-cell SMAD trajectories."""

from .artifacts import (
    load_holdout_manifest,
    preprocessor_from_checkpoint,
    save_holdout_manifest,
)
from .classical import ClassicalDetectorConfig, detect_classical_bursts
from .data import (
    ArchetypeBank,
    BurstEvent,
    DatasetSplits,
    SyntheticBurstConfig,
    SyntheticBurstDataset,
    TrajectoryPreprocessor,
    default_smad_archetypes,
    fit_archetype_bank,
    fit_preprocessor,
    generate_dataset_splits,
    generate_synthetic_bursts,
    mask_to_events,
    targets_to_tensor,
)
from .metrics import (
    BurstMetrics,
    ThresholdSelection,
    evaluate_burst_predictions,
    match_events,
    probabilities_to_mask,
    select_threshold,
)
from .model import BurstBiGRU, BurstCNN, BurstTCN, BurstUNet, count_parameters, create_burst_model
from .training import (
    EpochMetrics,
    SanityCheckResult,
    TrainingConfig,
    TrainingHistory,
    artifact_root,
    load_checkpoint,
    overfit_sanity_check,
    predict_probabilities,
    set_reproducible_seed,
    train_model,
)
from .tuning import (
    BurstArchitecture,
    BurstOptunaConfig,
    best_burst_model_configs,
    best_burst_tcn_configs,
    burst_trial_frame,
    optuna_parameter_importances,
    run_burst_model_search,
    run_burst_tcn_search,
)

__all__ = [
    "ArchetypeBank",
    "BurstEvent",
    "BurstMetrics",
    "BurstOptunaConfig",
    "BurstBiGRU",
    "BurstArchitecture",
    "BurstCNN",
    "BurstTCN",
    "BurstUNet",
    "ClassicalDetectorConfig",
    "DatasetSplits",
    "EpochMetrics",
    "SanityCheckResult",
    "SyntheticBurstConfig",
    "SyntheticBurstDataset",
    "ThresholdSelection",
    "TrainingConfig",
    "TrainingHistory",
    "TrajectoryPreprocessor",
    "artifact_root",
    "best_burst_model_configs",
    "best_burst_tcn_configs",
    "burst_trial_frame",
    "count_parameters",
    "create_burst_model",
    "default_smad_archetypes",
    "detect_classical_bursts",
    "evaluate_burst_predictions",
    "fit_archetype_bank",
    "fit_preprocessor",
    "generate_dataset_splits",
    "generate_synthetic_bursts",
    "load_checkpoint",
    "load_holdout_manifest",
    "mask_to_events",
    "match_events",
    "overfit_sanity_check",
    "optuna_parameter_importances",
    "predict_probabilities",
    "preprocessor_from_checkpoint",
    "probabilities_to_mask",
    "select_threshold",
    "save_holdout_manifest",
    "set_reproducible_seed",
    "run_burst_tcn_search",
    "run_burst_model_search",
    "targets_to_tensor",
    "train_model",
]
